server:
  port: 8080

spring:
  config:
    import:
      - optional:file:./application-jwt.yml


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    access-token-expiration-ms: ${APP_JWT_ACCESS_EXPIRATION_MS:900000} # 15 phút (15 * 60 * 1000)
    refresh-token-expiration-ms: ${APP_JWT_REFRESH_EXPIRATION_MS:604800000} # 7 ngày (7 * 24 * 60 * 60 * 1000)
  storage:
    minio:
      endpoint: ${APP_MINIO_ENDPOINT}
      access-key: ${APP_MINIO_ACCESS_KEY}
      secret-key: ${APP_MINIO_SECRET_KEY}
      bucket: ${APP_MINIO_BUCKET}
  date:
    default-format: "yyyy-MM-dd HH:mm:ss"
    timezone: "Asia/Ho_Chi_Minh"